jaffle_shop_bq:
  outputs:
    dev:
      dataset: jaffle_shop_bq_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/surya/diesel-command-384802-43939d9abf91.json
      location: US
      method: service-account
      priority: interactive
      project: diesel-command-384802
      threads: 4
      type: bigquery
  target: dev